USB_VID = 0x1B4F
USB_PID = 0x8D23
USB_PRODUCT = "DJHP_Board"
USB_MANUFACTURER = "Lambda"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

SUPEROPT_GC = 0
